version: '3.8'
services:
  app:
    container_name: student-app
    image: spring-docker-jakarta-postgres:v1
    ports:
      - 8088:8089
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=welcome
      - POSTGRES_USER=vinoth
      - POSTGRES_DB=db
      
volumes:
  postgres-data:      